// Code generated by "enumer -json -text -typederrors -type=FleetType"; DO NOT EDIT.

package fleettype

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/dmarkham/enumer/enumerrs"
	"strings"
)

const _FleetTypeName = "SINGLECTFSFTTCF"

var _FleetTypeIndex = [...]uint8{0, 6, 9, 12, 15}

const _FleetTypeLowerName = "singlectfsfttcf"

func (i FleetType) String() string {
	if i < 0 || i >= FleetType(len(_FleetTypeIndex)-1) {
		return fmt.Sprintf("FleetType(%d)", i)
	}
	return _FleetTypeName[_FleetTypeIndex[i]:_FleetTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _FleetTypeNoOp() {
	var x [1]struct{}
	_ = x[SINGLE-(0)]
	_ = x[CTF-(1)]
	_ = x[SFT-(2)]
	_ = x[TCF-(3)]
}

var _FleetTypeValues = []FleetType{SINGLE, CTF, SFT, TCF}

var _FleetTypeNameToValueMap = map[string]FleetType{
	_FleetTypeName[0:6]:        SINGLE,
	_FleetTypeLowerName[0:6]:   SINGLE,
	_FleetTypeName[6:9]:        CTF,
	_FleetTypeLowerName[6:9]:   CTF,
	_FleetTypeName[9:12]:       SFT,
	_FleetTypeLowerName[9:12]:  SFT,
	_FleetTypeName[12:15]:      TCF,
	_FleetTypeLowerName[12:15]: TCF,
}

var _FleetTypeNames = []string{
	_FleetTypeName[0:6],
	_FleetTypeName[6:9],
	_FleetTypeName[9:12],
	_FleetTypeName[12:15],
}

// FleetTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func FleetTypeString(s string) (FleetType, error) {
	if val, ok := _FleetTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _FleetTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, errors.Join(enumerrs.ErrValueInvalid, fmt.Errorf("%s does not belong to FleetType values", s))
}

// FleetTypeValues returns all values of the enum
func FleetTypeValues() []FleetType {
	return _FleetTypeValues
}

// FleetTypeStrings returns a slice of all String values of the enum
func FleetTypeStrings() []string {
	strs := make([]string, len(_FleetTypeNames))
	copy(strs, _FleetTypeNames)
	return strs
}

// IsAFleetType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i FleetType) IsAFleetType() bool {
	for _, v := range _FleetTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for FleetType
func (i FleetType) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for FleetType
func (i *FleetType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("FleetType should be a string, got %s", data)
	}

	var err error
	*i, err = FleetTypeString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for FleetType
func (i FleetType) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for FleetType
func (i *FleetType) UnmarshalText(text []byte) error {
	var err error
	*i, err = FleetTypeString(string(text))
	return err
}
