// Code generated by "enumer -json -text -typederrors -type=ShipType"; DO NOT EDIT.

package shiptype

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/dmarkham/enumer/enumerrs"
	"strings"
)

const _ShipTypeName = "DEDDCLCLTCACAVCVLFBBBBBBVCVBBBSSSSVAO_2AVLHACVBARASCTAO"

var _ShipTypeIndex = [...]uint8{0, 2, 4, 6, 9, 11, 14, 17, 20, 22, 25, 27, 30, 32, 35, 39, 41, 44, 47, 49, 51, 53, 55}

const _ShipTypeLowerName = "deddclcltcacavcvlfbbbbbbvcvbbbssssvao_2avlhacvbarasctao"

func (i ShipType) String() string {
	i -= 1
	if i < 0 || i >= ShipType(len(_ShipTypeIndex)-1) {
		return fmt.Sprintf("ShipType(%d)", i+1)
	}
	return _ShipTypeName[_ShipTypeIndex[i]:_ShipTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ShipTypeNoOp() {
	var x [1]struct{}
	_ = x[DE-(1)]
	_ = x[DD-(2)]
	_ = x[CL-(3)]
	_ = x[CLT-(4)]
	_ = x[CA-(5)]
	_ = x[CAV-(6)]
	_ = x[CVL-(7)]
	_ = x[FBB-(8)]
	_ = x[BB-(9)]
	_ = x[BBV-(10)]
	_ = x[CV-(11)]
	_ = x[BBB-(12)]
	_ = x[SS-(13)]
	_ = x[SSV-(14)]
	_ = x[AO_2-(15)]
	_ = x[AV-(16)]
	_ = x[LHA-(17)]
	_ = x[CVB-(18)]
	_ = x[AR-(19)]
	_ = x[AS-(20)]
	_ = x[CT-(21)]
	_ = x[AO-(22)]
}

var _ShipTypeValues = []ShipType{DE, DD, CL, CLT, CA, CAV, CVL, FBB, BB, BBV, CV, BBB, SS, SSV, AO_2, AV, LHA, CVB, AR, AS, CT, AO}

var _ShipTypeNameToValueMap = map[string]ShipType{
	_ShipTypeName[0:2]:        DE,
	_ShipTypeLowerName[0:2]:   DE,
	_ShipTypeName[2:4]:        DD,
	_ShipTypeLowerName[2:4]:   DD,
	_ShipTypeName[4:6]:        CL,
	_ShipTypeLowerName[4:6]:   CL,
	_ShipTypeName[6:9]:        CLT,
	_ShipTypeLowerName[6:9]:   CLT,
	_ShipTypeName[9:11]:       CA,
	_ShipTypeLowerName[9:11]:  CA,
	_ShipTypeName[11:14]:      CAV,
	_ShipTypeLowerName[11:14]: CAV,
	_ShipTypeName[14:17]:      CVL,
	_ShipTypeLowerName[14:17]: CVL,
	_ShipTypeName[17:20]:      FBB,
	_ShipTypeLowerName[17:20]: FBB,
	_ShipTypeName[20:22]:      BB,
	_ShipTypeLowerName[20:22]: BB,
	_ShipTypeName[22:25]:      BBV,
	_ShipTypeLowerName[22:25]: BBV,
	_ShipTypeName[25:27]:      CV,
	_ShipTypeLowerName[25:27]: CV,
	_ShipTypeName[27:30]:      BBB,
	_ShipTypeLowerName[27:30]: BBB,
	_ShipTypeName[30:32]:      SS,
	_ShipTypeLowerName[30:32]: SS,
	_ShipTypeName[32:35]:      SSV,
	_ShipTypeLowerName[32:35]: SSV,
	_ShipTypeName[35:39]:      AO_2,
	_ShipTypeLowerName[35:39]: AO_2,
	_ShipTypeName[39:41]:      AV,
	_ShipTypeLowerName[39:41]: AV,
	_ShipTypeName[41:44]:      LHA,
	_ShipTypeLowerName[41:44]: LHA,
	_ShipTypeName[44:47]:      CVB,
	_ShipTypeLowerName[44:47]: CVB,
	_ShipTypeName[47:49]:      AR,
	_ShipTypeLowerName[47:49]: AR,
	_ShipTypeName[49:51]:      AS,
	_ShipTypeLowerName[49:51]: AS,
	_ShipTypeName[51:53]:      CT,
	_ShipTypeLowerName[51:53]: CT,
	_ShipTypeName[53:55]:      AO,
	_ShipTypeLowerName[53:55]: AO,
}

var _ShipTypeNames = []string{
	_ShipTypeName[0:2],
	_ShipTypeName[2:4],
	_ShipTypeName[4:6],
	_ShipTypeName[6:9],
	_ShipTypeName[9:11],
	_ShipTypeName[11:14],
	_ShipTypeName[14:17],
	_ShipTypeName[17:20],
	_ShipTypeName[20:22],
	_ShipTypeName[22:25],
	_ShipTypeName[25:27],
	_ShipTypeName[27:30],
	_ShipTypeName[30:32],
	_ShipTypeName[32:35],
	_ShipTypeName[35:39],
	_ShipTypeName[39:41],
	_ShipTypeName[41:44],
	_ShipTypeName[44:47],
	_ShipTypeName[47:49],
	_ShipTypeName[49:51],
	_ShipTypeName[51:53],
	_ShipTypeName[53:55],
}

// ShipTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ShipTypeString(s string) (ShipType, error) {
	if val, ok := _ShipTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ShipTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, errors.Join(enumerrs.ErrValueInvalid, fmt.Errorf("%s does not belong to ShipType values", s))
}

// ShipTypeValues returns all values of the enum
func ShipTypeValues() []ShipType {
	return _ShipTypeValues
}

// ShipTypeStrings returns a slice of all String values of the enum
func ShipTypeStrings() []string {
	strs := make([]string, len(_ShipTypeNames))
	copy(strs, _ShipTypeNames)
	return strs
}

// IsAShipType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i ShipType) IsAShipType() bool {
	for _, v := range _ShipTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for ShipType
func (i ShipType) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for ShipType
func (i *ShipType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("ShipType should be a string, got %s", data)
	}

	var err error
	*i, err = ShipTypeString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for ShipType
func (i ShipType) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for ShipType
func (i *ShipType) UnmarshalText(text []byte) error {
	var err error
	*i, err = ShipTypeString(string(text))
	return err
}
