// Code generated by "enumer -json -text -typederrors -type=Cap"; DO NOT EDIT.

package firecap

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/dmarkham/enumer/enumerrs"
	"strings"
)

const (
	_CapName_0      = "AS"
	_CapLowerName_0 = "as"
	_CapName_1      = "BATTLE"
	_CapLowerName_1 = "battle"
	_CapName_2      = "NIGHT"
	_CapLowerName_2 = "night"
)

var (
	_CapIndex_0 = [...]uint8{0, 2}
	_CapIndex_1 = [...]uint8{0, 6}
	_CapIndex_2 = [...]uint8{0, 5}
)

func (i Cap) String() string {
	switch {
	case i == 170:
		return _CapName_0
	case i == 220:
		return _CapName_1
	case i == 360:
		return _CapName_2
	default:
		return fmt.Sprintf("Cap(%d)", i)
	}
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _CapNoOp() {
	var x [1]struct{}
	_ = x[AS-(170)]
	_ = x[BATTLE-(220)]
	_ = x[NIGHT-(360)]
}

var _CapValues = []Cap{AS, BATTLE, NIGHT}

var _CapNameToValueMap = map[string]Cap{
	_CapName_0[0:2]:      AS,
	_CapLowerName_0[0:2]: AS,
	_CapName_1[0:6]:      BATTLE,
	_CapLowerName_1[0:6]: BATTLE,
	_CapName_2[0:5]:      NIGHT,
	_CapLowerName_2[0:5]: NIGHT,
}

var _CapNames = []string{
	_CapName_0[0:2],
	_CapName_1[0:6],
	_CapName_2[0:5],
}

// CapString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func CapString(s string) (Cap, error) {
	if val, ok := _CapNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _CapNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, errors.Join(enumerrs.ErrValueInvalid, fmt.Errorf("%s does not belong to Cap values", s))
}

// CapValues returns all values of the enum
func CapValues() []Cap {
	return _CapValues
}

// CapStrings returns a slice of all String values of the enum
func CapStrings() []string {
	strs := make([]string, len(_CapNames))
	copy(strs, _CapNames)
	return strs
}

// IsACap returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Cap) IsACap() bool {
	for _, v := range _CapValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for Cap
func (i Cap) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for Cap
func (i *Cap) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("Cap should be a string, got %s", data)
	}

	var err error
	*i, err = CapString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for Cap
func (i Cap) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for Cap
func (i *Cap) UnmarshalText(text []byte) error {
	var err error
	*i, err = CapString(string(text))
	return err
}
