// Code generated by "enumer -json -text -typederrors -type=ABMode"; DO NOT EDIT.

package abmode

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/dmarkham/enumer/enumerrs"
	"strings"
)

const _ABModeName = "WAITBATTLEDEFENSE"

var _ABModeIndex = [...]uint8{0, 4, 10, 17}

const _ABModeLowerName = "waitbattledefense"

func (i ABMode) String() string {
	if i < 0 || i >= ABMode(len(_ABModeIndex)-1) {
		return fmt.Sprintf("ABMode(%d)", i)
	}
	return _ABModeName[_ABModeIndex[i]:_ABModeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ABModeNoOp() {
	var x [1]struct{}
	_ = x[WAIT-(0)]
	_ = x[BATTLE-(1)]
	_ = x[DEFENSE-(2)]
}

var _ABModeValues = []ABMode{WAIT, BATTLE, DEFENSE}

var _ABModeNameToValueMap = map[string]ABMode{
	_ABModeName[0:4]:        WAIT,
	_ABModeLowerName[0:4]:   WAIT,
	_ABModeName[4:10]:       BATTLE,
	_ABModeLowerName[4:10]:  BATTLE,
	_ABModeName[10:17]:      DEFENSE,
	_ABModeLowerName[10:17]: DEFENSE,
}

var _ABModeNames = []string{
	_ABModeName[0:4],
	_ABModeName[4:10],
	_ABModeName[10:17],
}

// ABModeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ABModeString(s string) (ABMode, error) {
	if val, ok := _ABModeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ABModeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, errors.Join(enumerrs.ErrValueInvalid, fmt.Errorf("%s does not belong to ABMode values", s))
}

// ABModeValues returns all values of the enum
func ABModeValues() []ABMode {
	return _ABModeValues
}

// ABModeStrings returns a slice of all String values of the enum
func ABModeStrings() []string {
	strs := make([]string, len(_ABModeNames))
	copy(strs, _ABModeNames)
	return strs
}

// IsAABMode returns "true" if the value is listed in the enum definition. "false" otherwise
func (i ABMode) IsAABMode() bool {
	for _, v := range _ABModeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for ABMode
func (i ABMode) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for ABMode
func (i *ABMode) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("ABMode should be a string, got %s", data)
	}

	var err error
	*i, err = ABModeString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for ABMode
func (i ABMode) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for ABMode
func (i *ABMode) UnmarshalText(text []byte) error {
	var err error
	*i, err = ABModeString(string(text))
	return err
}
