// Code generated by "enumer -json -text -typederrors -type=Difficulty"; DO NOT EDIT.

package difficulty

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/dmarkham/enumer/enumerrs"
	"strings"
)

const _DifficultyName = "HARDMEDIUMEASYCASUAL"

var _DifficultyIndex = [...]uint8{0, 4, 10, 14, 20}

const _DifficultyLowerName = "hardmediumeasycasual"

func (i Difficulty) String() string {
	if i < 0 || i >= Difficulty(len(_DifficultyIndex)-1) {
		return fmt.Sprintf("Difficulty(%d)", i)
	}
	return _DifficultyName[_DifficultyIndex[i]:_DifficultyIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _DifficultyNoOp() {
	var x [1]struct{}
	_ = x[HARD-(0)]
	_ = x[MEDIUM-(1)]
	_ = x[EASY-(2)]
	_ = x[CASUAL-(3)]
}

var _DifficultyValues = []Difficulty{HARD, MEDIUM, EASY, CASUAL}

var _DifficultyNameToValueMap = map[string]Difficulty{
	_DifficultyName[0:4]:        HARD,
	_DifficultyLowerName[0:4]:   HARD,
	_DifficultyName[4:10]:       MEDIUM,
	_DifficultyLowerName[4:10]:  MEDIUM,
	_DifficultyName[10:14]:      EASY,
	_DifficultyLowerName[10:14]: EASY,
	_DifficultyName[14:20]:      CASUAL,
	_DifficultyLowerName[14:20]: CASUAL,
}

var _DifficultyNames = []string{
	_DifficultyName[0:4],
	_DifficultyName[4:10],
	_DifficultyName[10:14],
	_DifficultyName[14:20],
}

// DifficultyString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func DifficultyString(s string) (Difficulty, error) {
	if val, ok := _DifficultyNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _DifficultyNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, errors.Join(enumerrs.ErrValueInvalid, fmt.Errorf("%s does not belong to Difficulty values", s))
}

// DifficultyValues returns all values of the enum
func DifficultyValues() []Difficulty {
	return _DifficultyValues
}

// DifficultyStrings returns a slice of all String values of the enum
func DifficultyStrings() []string {
	strs := make([]string, len(_DifficultyNames))
	copy(strs, _DifficultyNames)
	return strs
}

// IsADifficulty returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Difficulty) IsADifficulty() bool {
	for _, v := range _DifficultyValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for Difficulty
func (i Difficulty) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for Difficulty
func (i *Difficulty) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("Difficulty should be a string, got %s", data)
	}

	var err error
	*i, err = DifficultyString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for Difficulty
func (i Difficulty) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for Difficulty
func (i *Difficulty) UnmarshalText(text []byte) error {
	var err error
	*i, err = DifficultyString(string(text))
	return err
}
