// Code generated by "enumer -json -text -typederrors -type=SupportType"; DO NOT EDIT.

package supporttype

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/dmarkham/enumer/enumerrs"
	"strings"
)

const _SupportTypeName = "SHELLINGAIRSTRIKEANTI_SUBMARINELONG_RANGE_TORPEDONOT_FOUND_DDNONE"

var _SupportTypeIndex = [...]uint8{0, 8, 17, 31, 49, 61, 65}

const _SupportTypeLowerName = "shellingairstrikeanti_submarinelong_range_torpedonot_found_ddnone"

func (i SupportType) String() string {
	if i < 0 || i >= SupportType(len(_SupportTypeIndex)-1) {
		return fmt.Sprintf("SupportType(%d)", i)
	}
	return _SupportTypeName[_SupportTypeIndex[i]:_SupportTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _SupportTypeNoOp() {
	var x [1]struct{}
	_ = x[SHELLING-(0)]
	_ = x[AIRSTRIKE-(1)]
	_ = x[ANTI_SUBMARINE-(2)]
	_ = x[LONG_RANGE_TORPEDO-(3)]
	_ = x[NOT_FOUND_DD-(4)]
	_ = x[NONE-(5)]
}

var _SupportTypeValues = []SupportType{SHELLING, AIRSTRIKE, ANTI_SUBMARINE, LONG_RANGE_TORPEDO, NOT_FOUND_DD, NONE}

var _SupportTypeNameToValueMap = map[string]SupportType{
	_SupportTypeName[0:8]:        SHELLING,
	_SupportTypeLowerName[0:8]:   SHELLING,
	_SupportTypeName[8:17]:       AIRSTRIKE,
	_SupportTypeLowerName[8:17]:  AIRSTRIKE,
	_SupportTypeName[17:31]:      ANTI_SUBMARINE,
	_SupportTypeLowerName[17:31]: ANTI_SUBMARINE,
	_SupportTypeName[31:49]:      LONG_RANGE_TORPEDO,
	_SupportTypeLowerName[31:49]: LONG_RANGE_TORPEDO,
	_SupportTypeName[49:61]:      NOT_FOUND_DD,
	_SupportTypeLowerName[49:61]: NOT_FOUND_DD,
	_SupportTypeName[61:65]:      NONE,
	_SupportTypeLowerName[61:65]: NONE,
}

var _SupportTypeNames = []string{
	_SupportTypeName[0:8],
	_SupportTypeName[8:17],
	_SupportTypeName[17:31],
	_SupportTypeName[31:49],
	_SupportTypeName[49:61],
	_SupportTypeName[61:65],
}

// SupportTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func SupportTypeString(s string) (SupportType, error) {
	if val, ok := _SupportTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _SupportTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, errors.Join(enumerrs.ErrValueInvalid, fmt.Errorf("%s does not belong to SupportType values", s))
}

// SupportTypeValues returns all values of the enum
func SupportTypeValues() []SupportType {
	return _SupportTypeValues
}

// SupportTypeStrings returns a slice of all String values of the enum
func SupportTypeStrings() []string {
	strs := make([]string, len(_SupportTypeNames))
	copy(strs, _SupportTypeNames)
	return strs
}

// IsASupportType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i SupportType) IsASupportType() bool {
	for _, v := range _SupportTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for SupportType
func (i SupportType) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for SupportType
func (i *SupportType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("SupportType should be a string, got %s", data)
	}

	var err error
	*i, err = SupportTypeString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for SupportType
func (i SupportType) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for SupportType
func (i *SupportType) UnmarshalText(text []byte) error {
	var err error
	*i, err = SupportTypeString(string(text))
	return err
}
