// Code generated by "enumer -json -text -typederrors -type=CellType"; DO NOT EDIT.

package celltype

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/dmarkham/enumer/enumerrs"
	"strings"
)

const _CellTypeName = "NORMALGRANDAIR_RAIDNIGHTHIGH_AIR_RAIDAERIAL_COMBATSUPER_HIGH_AIR_RAIDAIR_SUPPORTED_ASWRADAR"

var _CellTypeIndex = [...]uint8{0, 6, 11, 19, 24, 37, 50, 69, 86, 91}

const _CellTypeLowerName = "normalgrandair_raidnighthigh_air_raidaerial_combatsuper_high_air_raidair_supported_aswradar"

func (i CellType) String() string {
	i -= 1
	if i < 0 || i >= CellType(len(_CellTypeIndex)-1) {
		return fmt.Sprintf("CellType(%d)", i+1)
	}
	return _CellTypeName[_CellTypeIndex[i]:_CellTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _CellTypeNoOp() {
	var x [1]struct{}
	_ = x[NORMAL-(1)]
	_ = x[GRAND-(2)]
	_ = x[AIR_RAID-(3)]
	_ = x[NIGHT-(4)]
	_ = x[HIGH_AIR_RAID-(5)]
	_ = x[AERIAL_COMBAT-(6)]
	_ = x[SUPER_HIGH_AIR_RAID-(7)]
	_ = x[AIR_SUPPORTED_ASW-(8)]
	_ = x[RADAR-(9)]
}

var _CellTypeValues = []CellType{NORMAL, GRAND, AIR_RAID, NIGHT, HIGH_AIR_RAID, AERIAL_COMBAT, SUPER_HIGH_AIR_RAID, AIR_SUPPORTED_ASW, RADAR}

var _CellTypeNameToValueMap = map[string]CellType{
	_CellTypeName[0:6]:        NORMAL,
	_CellTypeLowerName[0:6]:   NORMAL,
	_CellTypeName[6:11]:       GRAND,
	_CellTypeLowerName[6:11]:  GRAND,
	_CellTypeName[11:19]:      AIR_RAID,
	_CellTypeLowerName[11:19]: AIR_RAID,
	_CellTypeName[19:24]:      NIGHT,
	_CellTypeLowerName[19:24]: NIGHT,
	_CellTypeName[24:37]:      HIGH_AIR_RAID,
	_CellTypeLowerName[24:37]: HIGH_AIR_RAID,
	_CellTypeName[37:50]:      AERIAL_COMBAT,
	_CellTypeLowerName[37:50]: AERIAL_COMBAT,
	_CellTypeName[50:69]:      SUPER_HIGH_AIR_RAID,
	_CellTypeLowerName[50:69]: SUPER_HIGH_AIR_RAID,
	_CellTypeName[69:86]:      AIR_SUPPORTED_ASW,
	_CellTypeLowerName[69:86]: AIR_SUPPORTED_ASW,
	_CellTypeName[86:91]:      RADAR,
	_CellTypeLowerName[86:91]: RADAR,
}

var _CellTypeNames = []string{
	_CellTypeName[0:6],
	_CellTypeName[6:11],
	_CellTypeName[11:19],
	_CellTypeName[19:24],
	_CellTypeName[24:37],
	_CellTypeName[37:50],
	_CellTypeName[50:69],
	_CellTypeName[69:86],
	_CellTypeName[86:91],
}

// CellTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func CellTypeString(s string) (CellType, error) {
	if val, ok := _CellTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _CellTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, errors.Join(enumerrs.ErrValueInvalid, fmt.Errorf("%s does not belong to CellType values", s))
}

// CellTypeValues returns all values of the enum
func CellTypeValues() []CellType {
	return _CellTypeValues
}

// CellTypeStrings returns a slice of all String values of the enum
func CellTypeStrings() []string {
	strs := make([]string, len(_CellTypeNames))
	copy(strs, _CellTypeNames)
	return strs
}

// IsACellType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i CellType) IsACellType() bool {
	for _, v := range _CellTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for CellType
func (i CellType) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for CellType
func (i *CellType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("CellType should be a string, got %s", data)
	}

	var err error
	*i, err = CellTypeString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for CellType
func (i CellType) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for CellType
func (i *CellType) UnmarshalText(text []byte) error {
	var err error
	*i, err = CellTypeString(string(text))
	return err
}
