// Code generated by "enumer -json -text -typederrors -type=Formation"; DO NOT EDIT.

package formation

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/dmarkham/enumer/enumerrs"
	"strings"
)

const (
	_FormationName_0      = "LINE_AHEADDOUBLE_LINEDIAMONDECHELONLINE_ABREASTVANGUARD"
	_FormationLowerName_0 = "line_aheaddouble_linediamondechelonline_abreastvanguard"
	_FormationName_1      = "FORMATION1FORMATION2FORMATION3FORMATION4"
	_FormationLowerName_1 = "formation1formation2formation3formation4"
)

var (
	_FormationIndex_0 = [...]uint8{0, 10, 21, 28, 35, 47, 55}
	_FormationIndex_1 = [...]uint8{0, 10, 20, 30, 40}
)

func (i Formation) String() string {
	switch {
	case 1 <= i && i <= 6:
		i -= 1
		return _FormationName_0[_FormationIndex_0[i]:_FormationIndex_0[i+1]]
	case 11 <= i && i <= 14:
		i -= 11
		return _FormationName_1[_FormationIndex_1[i]:_FormationIndex_1[i+1]]
	default:
		return fmt.Sprintf("Formation(%d)", i)
	}
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _FormationNoOp() {
	var x [1]struct{}
	_ = x[LINE_AHEAD-(1)]
	_ = x[DOUBLE_LINE-(2)]
	_ = x[DIAMOND-(3)]
	_ = x[ECHELON-(4)]
	_ = x[LINE_ABREAST-(5)]
	_ = x[VANGUARD-(6)]
	_ = x[FORMATION1-(11)]
	_ = x[FORMATION2-(12)]
	_ = x[FORMATION3-(13)]
	_ = x[FORMATION4-(14)]
}

var _FormationValues = []Formation{LINE_AHEAD, DOUBLE_LINE, DIAMOND, ECHELON, LINE_ABREAST, VANGUARD, FORMATION1, FORMATION2, FORMATION3, FORMATION4}

var _FormationNameToValueMap = map[string]Formation{
	_FormationName_0[0:10]:       LINE_AHEAD,
	_FormationLowerName_0[0:10]:  LINE_AHEAD,
	_FormationName_0[10:21]:      DOUBLE_LINE,
	_FormationLowerName_0[10:21]: DOUBLE_LINE,
	_FormationName_0[21:28]:      DIAMOND,
	_FormationLowerName_0[21:28]: DIAMOND,
	_FormationName_0[28:35]:      ECHELON,
	_FormationLowerName_0[28:35]: ECHELON,
	_FormationName_0[35:47]:      LINE_ABREAST,
	_FormationLowerName_0[35:47]: LINE_ABREAST,
	_FormationName_0[47:55]:      VANGUARD,
	_FormationLowerName_0[47:55]: VANGUARD,
	_FormationName_1[0:10]:       FORMATION1,
	_FormationLowerName_1[0:10]:  FORMATION1,
	_FormationName_1[10:20]:      FORMATION2,
	_FormationLowerName_1[10:20]: FORMATION2,
	_FormationName_1[20:30]:      FORMATION3,
	_FormationLowerName_1[20:30]: FORMATION3,
	_FormationName_1[30:40]:      FORMATION4,
	_FormationLowerName_1[30:40]: FORMATION4,
}

var _FormationNames = []string{
	_FormationName_0[0:10],
	_FormationName_0[10:21],
	_FormationName_0[21:28],
	_FormationName_0[28:35],
	_FormationName_0[35:47],
	_FormationName_0[47:55],
	_FormationName_1[0:10],
	_FormationName_1[10:20],
	_FormationName_1[20:30],
	_FormationName_1[30:40],
}

// FormationString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func FormationString(s string) (Formation, error) {
	if val, ok := _FormationNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _FormationNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, errors.Join(enumerrs.ErrValueInvalid, fmt.Errorf("%s does not belong to Formation values", s))
}

// FormationValues returns all values of the enum
func FormationValues() []Formation {
	return _FormationValues
}

// FormationStrings returns a slice of all String values of the enum
func FormationStrings() []string {
	strs := make([]string, len(_FormationNames))
	copy(strs, _FormationNames)
	return strs
}

// IsAFormation returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Formation) IsAFormation() bool {
	for _, v := range _FormationValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for Formation
func (i Formation) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for Formation
func (i *Formation) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("Formation should be a string, got %s", data)
	}

	var err error
	*i, err = FormationString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for Formation
func (i Formation) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for Formation
func (i *Formation) UnmarshalText(text []byte) error {
	var err error
	*i, err = FormationString(string(text))
	return err
}
