// Code generated by "enumer -json -text -typederrors -type=AirState"; DO NOT EDIT.

package airstate

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/dmarkham/enumer/enumerrs"
	"strings"
)

const _AirStateName = "KAKUHOYUSEIKINKORESSEISOSHITSUNONE"

var _AirStateIndex = [...]uint8{0, 6, 11, 16, 22, 30, 34}

const _AirStateLowerName = "kakuhoyuseikinkoresseisoshitsunone"

func (i AirState) String() string {
	if i < 0 || i >= AirState(len(_AirStateIndex)-1) {
		return fmt.Sprintf("AirState(%d)", i)
	}
	return _AirStateName[_AirStateIndex[i]:_AirStateIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _AirStateNoOp() {
	var x [1]struct{}
	_ = x[KAKUHO-(0)]
	_ = x[YUSEI-(1)]
	_ = x[KINKO-(2)]
	_ = x[RESSEI-(3)]
	_ = x[SOSHITSU-(4)]
	_ = x[NONE-(5)]
}

var _AirStateValues = []AirState{KAKUHO, YUSEI, KINKO, RESSEI, SOSHITSU, NONE}

var _AirStateNameToValueMap = map[string]AirState{
	_AirStateName[0:6]:        KAKUHO,
	_AirStateLowerName[0:6]:   KAKUHO,
	_AirStateName[6:11]:       YUSEI,
	_AirStateLowerName[6:11]:  YUSEI,
	_AirStateName[11:16]:      KINKO,
	_AirStateLowerName[11:16]: KINKO,
	_AirStateName[16:22]:      RESSEI,
	_AirStateLowerName[16:22]: RESSEI,
	_AirStateName[22:30]:      SOSHITSU,
	_AirStateLowerName[22:30]: SOSHITSU,
	_AirStateName[30:34]:      NONE,
	_AirStateLowerName[30:34]: NONE,
}

var _AirStateNames = []string{
	_AirStateName[0:6],
	_AirStateName[6:11],
	_AirStateName[11:16],
	_AirStateName[16:22],
	_AirStateName[22:30],
	_AirStateName[30:34],
}

// AirStateString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func AirStateString(s string) (AirState, error) {
	if val, ok := _AirStateNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _AirStateNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, errors.Join(enumerrs.ErrValueInvalid, fmt.Errorf("%s does not belong to AirState values", s))
}

// AirStateValues returns all values of the enum
func AirStateValues() []AirState {
	return _AirStateValues
}

// AirStateStrings returns a slice of all String values of the enum
func AirStateStrings() []string {
	strs := make([]string, len(_AirStateNames))
	copy(strs, _AirStateNames)
	return strs
}

// IsAAirState returns "true" if the value is listed in the enum definition. "false" otherwise
func (i AirState) IsAAirState() bool {
	for _, v := range _AirStateValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for AirState
func (i AirState) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for AirState
func (i *AirState) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("AirState should be a string, got %s", data)
	}

	var err error
	*i, err = AirStateString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for AirState
func (i AirState) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for AirState
func (i *AirState) UnmarshalText(text []byte) error {
	var err error
	*i, err = AirStateString(string(text))
	return err
}
